extends Node

func _ready() -> void:
	var c := GameAPI.content
	var a := SlotContainer.new(c, 2)
	assert(a.insert({"id": "core:dirt", "count": 100}).added == 100)
	assert(a.stack_at(0).count == 64 and a.stack_at(1).count == 36)
	var before := a.snapshot()
	assert(a.insert({"id": "core:dirt", "count": 40}, true).added == 0)
	assert(a.snapshot() == before)
	var partial := a.insert({"id": "core:dirt", "count": 40})
	assert(partial.added == 28 and partial.remainder.count == 12)
	var b := SlotContainer.new(c, 2)
	assert(a.transfer_to(b, 0, 0, 16).moved == 16)
	assert(a.count("core:dirt") + b.count("core:dirt") == 128)
	assert(b.transfer_to(b, 0, 1, 8).moved == 8)
	assert(b.stack_at(0).count == 8 and b.stack_at(1).count == 8)
	before = b.snapshot()
	assert(not b.transfer_to(b, 0, 0).success)
	assert(b.snapshot() == before)
	var metadata := SlotContainer.new(c, 2)
	metadata.insert({"id": "core:stick", "count": 1, "metadata": {"quality": "rare"}})
	metadata.insert({"id": "core:stick", "count": 1, "metadata": {"quality": "common"}})
	assert(metadata.stack_at(0).metadata != metadata.stack_at(1).metadata)
	var copy := metadata.stack_at(0)
	copy.metadata.quality = "changed"
	assert(metadata.stack_at(0).metadata.quality == "rare")
	var filtered := SlotContainer.new(c, 1)
	filtered.set_filter(0, func(stack: Dictionary) -> bool: return stack.id == "core:stone")
	assert(not metadata.transfer_to(filtered, 0, 0).success)
	assert(metadata.count("core:stick") == 2)
	var recipe := SlotContainer.new(c, 1)
	recipe.insert({"id": "core:dirt", "count": 64})
	before = recipe.snapshot()
	assert(not recipe.exchange({"core:dirt": 1}, {"id": "core:stone", "count": 1}))
	assert(recipe.snapshot() == before)
	assert(recipe.exchange({"core:dirt": 64}, {"id": "core:stone", "count": 1}, false))
	assert(recipe.snapshot() == before)
	assert(recipe.exchange({"core:dirt": 64}, {"id": "core:stone", "count": 1}))
	assert(recipe.count("core:dirt") == 0 and recipe.count("core:stone") == 1)
	var inv := Inventory.new()
	var legacy := {"items": [{"id": "core:dirt", "count": 2500}, {"id": "missing:relic", "count": 2}], "hotbar": ["core:dirt"], "selected_slot": 0}
	inv.load_snapshot(legacy)
	assert(inv.migrated_legacy)
	assert(inv.get_selected_item_id() == "core:dirt")
	var total := inv.get_item_count("core:dirt")
	for stack in inv.recovery:
		if stack.id == "core:dirt":
			total += int(stack.count)
	assert(total == 2500)
	assert(inv.recovery.any(func(stack: Dictionary) -> bool: return stack.id == "missing:relic"))
	var old_slots: Array[Dictionary] = []
	for i in range(32):
		old_slots.append({"id": "core:dirt", "count": i + 1})
	var migrated := Inventory.new()
	migrated.load_snapshot({"version": 2, "slots": old_slots, "selected_slot": 7})
	assert(migrated.get_slot(8).is_empty() and migrated.get_slot(9).is_empty())
	assert(migrated.get_slot(10).count == 9 and migrated.get_slot(33).count == 32)
	assert(migrated.get_item_count("core:dirt") == 528)
	assert(migrated.selected_slot == 7)
	migrated.set_selected_slot(9)
	assert(migrated.selected_slot == 9)
	migrated.free()
	var snapshot := inv.get_snapshot()
	var restored := Inventory.new()
	restored.load_snapshot(snapshot)
	assert(restored.get_snapshot() == snapshot)
	assert(not restored.migrated_legacy)
	assert(inv.container.size() == 34)
	assert(not inv.equip(0, 0).success)
	inv.container.take(31, 64)
	assert(inv.recover_stack(0).added > 0)
	var full := Inventory.new()
	assert(full.add_item("core:dirt", 2176))
	full.grant_item("core:stone", 3)
	assert(full.recovery.size() == 1 and full.recovery[0].count == 3)
	assert(full.get_item_count("core:stone") == 0)
	assert(not full.craft_transaction({"core:dirt": 1}, {"id": "core:stone", "count": 1}))
	assert(full.get_item_count("core:dirt") == 2176)
	var save_game: Node = load("res://core/network/GameManager.gd").new()
	var player := CharacterBody3D.new()
	full.name = "Inventory"
	player.add_child(full)
	save_game._local_player = player
	save_game._state_path = "user://inventory_foundation_tests/%s.player.json" % Time.get_ticks_usec()
	save_game._save_local_player_state()
	assert(FileAccess.file_exists(save_game._state_path))
	full.remove_item("core:dirt", 1)
	save_game._save_local_player_state()
	assert(FileAccess.file_exists(save_game._state_path + ".bak"))
	var saved: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(save_game._state_path))
	assert(saved == JSON.parse_string(JSON.stringify(full.get_snapshot())))
	assert(not FileAccess.file_exists(save_game._state_path + ".tmp"))
	var ui: CanvasLayer = load("res://scenes/inventoryui/inventory.tscn").instantiate()
	add_child(ui)
	ui._bind_player(player)
	ui.inventory_open = true
	ui._refresh()
	assert(ui.slot_counts[0].text == "x64")
	assert(ui.recovery_button.visible)
	ui.recovery_button.pressed.emit()
	ui.queue_free()
	save_game.free()
	player.free()
	inv.free()
	restored.free()
	print("Inventory foundation smoke passed: capacity, transactions, metadata, migration and recovery")
	get_tree().quit()
